version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/.github"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 12

- package-ecosystem: "npm"
  directory: "/ui"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 12
  ignore:
  - # @docker/docker-mui-theme only supports max react 18.x.x
    dependency-name: "react"
    versions: [">=19.0.0"]
  - # @docker/docker-mui-theme only supports max react 18.x.x
    dependency-name: "react-dom"
    versions: [">=19.0.0"]
  - # @docker/docker-mui-theme only supports max @mui/material 6.x.x
    dependency-name: "@mui/material"
    versions: [">=7.0.0"]

- package-ecosystem: "gomod"
  directory: "/installer"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 12
