services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - "11505:8080"
    volumes:
      - ./linux/searxng:/etc/searxng
    restart: always
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    ports:
      - "11600:8000"
    volumes:
      - ./linux/mcpo:/etc/mcpo
      - /etc/rancher/k3s:/etc/rancher/k3s
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "/etc/mcpo/entrypoint.sh"]
    restart: always
  open-webui:
    image: ghcr.io/open-webui/open-webui@sha256:fe7a6870ec6b2fd540c0f2007e6aa812dc4bf04a2d0a305bb344eeb10de0a7b7  # v0.6.5
    ports:
      - "11500:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - DEFAULT_USER_ROLE=user
      - WEBUI_AUTH=False
      - WEBUI_SESSION_COOKIE_SAME_SITE=None
      - WEBUI_SESSION_COOKIE_SECURE=True
      - ENABLE_RAG_WEB_SEARCH=True
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - RAG_WEB_SEARCH_ENGINE=searxng
      - DEFAULT_MODELS=tinyllama
      - SEARXNG_QUERY_URL=http://host.docker.internal:11505
    restart: always

volumes:
  open-webui:
