services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - "127.0.0.1:11505:8080"
    volumes:
      - ./linux/searxng:/etc/searxng
    restart: always
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    ports:
      - "127.0.0.1:11600:8000"
    volumes:
      - ./linux/mcpo:/etc/mcpo
      - /etc/rancher/k3s:/etc/rancher/k3s
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "/etc/mcpo/entrypoint.sh"]
    restart: always
  open-webui:
    image: ghcr.io/open-webui/open-webui@sha256:fda936056184035a71a9ad5ff3721530ff061f16bc3907efb33a3201ba87ccfe  # v0.6.15
    ports:
      - "127.0.0.1:11500:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - DEFAULT_USER_ROLE=user
      - WEBUI_AUTH=False
      - WEBUI_SESSION_COOKIE_SAME_SITE=None
      - WEBUI_SESSION_COOKIE_SECURE=True
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - DEFAULT_MODELS=tinyllama
      - SEARXNG_QUERY_URL=http://host.docker.internal:11505
    restart: always

volumes:
  open-webui:
