name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
